{{- if .Values.db3.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: db3
  labels:
    app: postgres
    instance: db3
spec:
  clusterIP: None
  ports:
    - name: "postgres"
      port: 5432
      targetPort: 5432
  selector:
    app: postgres
    instance: db3
{{- end }}