apiVersion: v2
name: my-app
description: A Helm chart for my application
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: redis

    version: "22.0.7"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: kafka
    version: "32.4.3"
    repository: "https://charts.bitnami.com/bitnami"
    condition: kafka.enabled