{{- if .Values.app1.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: app1
  name: app1
  namespace: {{ .Values.global.namespace | quote }}
spec:
  ports:
    - name: "http"
      port: 8081
      targetPort: 8081
  selector:
    io.kompose.service: app1
{{- end }}