{{- if .Values.db4.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: db4
  labels:
    app: mongo
    instance: db4
spec:
  clusterIP: None
  ports:
    - name: "mongo"
      port: 27017
      targetPort: 27017
  selector:
    app: mongo
    instance: db4
{{- end }}