{{- if .Values.db1.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: db1
  labels:
    app: postgres
    instance: db1
spec:
  clusterIP: None
  ports:
    - name: "postgres"
      port: 5432
      targetPort: 5432
  selector:
    app: postgres
    instance: db1
{{- end }}