{{- if .Values.app5.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: app5
  name: app5
  namespace: {{ .Values.global.namespace | quote }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    io.kompose.service: app5
{{- end }}