{{- if .Values.app2.enabled }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: app2
  name: app2
  namespace: {{ .Values.global.namespace | quote }}
spec:
  ports:
    - name: "http"
      port: 8082
      targetPort: 8082
  selector:
    io.kompose.service: app2
{{- end }}