{{- if .Values.app3.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: app3
  name: app3
  namespace: {{ .Values.global.namespace | quote }}
spec:
  ports:
    - name: "http"
      port: 8083
      targetPort: 8083
  selector:
    io.kompose.service: app3
{{- end }}