{{- if .Values.db2.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: db2
  labels:
    app: postgres
    instance: db2
spec:
  clusterIP: None
  ports:
    - name: "postgres"
      port: 5432
      targetPort: 5432
  selector:
    app: postgres
    instance: db2
{{- end }}